import {it,expect,vi,afterEach} from 'vitest';
import {compactCommand} from '../src/commands/compact.js';
vi.mock('../src/daemon-lifecycle.js',()=>({getDaemonStatus:async()=>({state:'running',port:7433}),getDaemonUrl:()=> 'http://fixture'}));
afterEach(()=>{vi.restoreAllMocks();process.exitCode=0;});
function fixture(){vi.spyOn(console,'log').mockImplementation(()=>{});vi.spyOn(console,'error').mockImplementation(()=>{});const post=vi.fn(async()=>({status:200,data:{stage:'compact-sent'}}));const get=vi.fn(async()=>({status:200,data:{preparation:null}}));return{post,get,cmd:compactCommand({lifecycleDeps:{} as any,clientFactory:()=>({post,get}) as any})};}
it('manual request retains 180s HTTP ceiling and skip-map applies only to this invocation',async()=>{const f=fixture();await f.cmd.parseAsync(['node','rig','writer@demo','--skip-map']);expect(f.post).toHaveBeenCalledWith('/api/compaction/trigger',{session:'writer@demo',skipMap:true},expect.objectContaining({timeoutMs:180000}));});
it('ordinary manual request does not implicitly skip the map',async()=>{const f=fixture();await f.cmd.parseAsync(['node','rig','writer@demo']);expect(f.post.mock.calls[0]?.[1]).toEqual({session:'writer@demo'});});
it('state is read-only; cancel does not trigger',async()=>{const f=fixture();await f.cmd.parseAsync(['node','rig','writer@demo','--state']);expect(f.post).not.toHaveBeenCalled();expect(f.get).toHaveBeenCalledWith('/api/compaction/state?session=writer%40demo');const g=fixture();await g.cmd.parseAsync(['node','rig','writer@demo','--cancel']);expect(g.post.mock.calls[0]?.[0]).toBe('/api/compaction/cancel');});
it('contradictory explicit actions do not contact daemon',async()=>{const f=fixture();await f.cmd.parseAsync(['node','rig','writer@demo','--cancel','--skip-map']);expect(f.post).not.toHaveBeenCalled();expect(f.get).not.toHaveBeenCalled();expect(process.exitCode).toBe(1);});
