#!/bin/bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLI_DIR="$REPO_ROOT/packages/cli"
DAEMON_DIR="$REPO_ROOT/packages/daemon"
UI_DIR="$REPO_ROOT/packages/ui"
TUI_DIR="$REPO_ROOT/packages/tui"

echo "=== OpenRig Package Build ==="
echo "Repo root: $REPO_ROOT"
echo ""

# 1. Clean previous build artifacts
echo "[1/6] Cleaning previous artifacts..."
rm -rf "$CLI_DIR/daemon" "$CLI_DIR/ui" "$CLI_DIR/tui"

# 2. Build daemon
echo "[2/6] Building daemon..."
(cd "$DAEMON_DIR" && npm run build)

# 3. Build UI
echo "[3/6] Building UI..."
(cd "$UI_DIR" && npm run build)

# 4. Build TUI
echo "[4/6] Building TUI..."
(cd "$TUI_DIR" && npm run build)

# 5. Build CLI
echo "[5/6] Building CLI..."
(cd "$CLI_DIR" && npm run build)

# 6. Assemble: copy daemon + UI + TUI into CLI package
echo "[6/6] Assembling package..."

# OPR.0.4.4.11 FR-6 — deploy-identity stamp. Computed ONCE here (the runtime
# worktree is at the SHA — available at build), then written as the compiled
# build-info module into EACH package's dist (per-package generated modules;
# the committed src/build-info.ts files stay the honest dev stubs). No
# runtime cross-package import.
STAMP_SEMVER="$(node -p "require('$CLI_DIR/package.json').version")"
STAMP_COMMIT="$(git -C "$REPO_ROOT" rev-parse HEAD)"
if [ -n "$(git -C "$REPO_ROOT" status --porcelain)" ]; then STAMP_DIRTY=true; else STAMP_DIRTY=false; fi
STAMP_BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "Build identity: ${STAMP_SEMVER} (${STAMP_COMMIT}) dirty=${STAMP_DIRTY} at ${STAMP_BUILT_AT}"

write_build_info() {
  cat > "$1" <<EOF
// GENERATED by scripts/build-package.sh — the packaged build-identity stamp.
export const BUILD_INFO = {
  semver: "${STAMP_SEMVER}",
  commit: "${STAMP_COMMIT}",
  dirty: ${STAMP_DIRTY},
  builtAt: "${STAMP_BUILT_AT}",
};
export function stampFields(info = BUILD_INFO) {
  if (!info.commit) return {};
  return { semver: info.semver, commit: info.commit, dirty: info.dirty, builtAt: info.builtAt };
}
EOF
}
write_build_info "$DAEMON_DIR/dist/build-info.js"
write_build_info "$CLI_DIR/dist/build-info.js"

# Daemon: dist + assets + specs
mkdir -p "$CLI_DIR/daemon/dist"
cp -r "$DAEMON_DIR/dist/"* "$CLI_DIR/daemon/dist/"

if [ -d "$DAEMON_DIR/assets" ]; then
  cp -r "$DAEMON_DIR/assets" "$CLI_DIR/daemon/assets"
fi

if [ -d "$DAEMON_DIR/specs" ]; then
  cp -r "$DAEMON_DIR/specs" "$CLI_DIR/daemon/specs"
fi

# Built-in policies (OPR.0.4.8.3): canonical source packages/daemon/policies/builtin/
# ships with the daemon; startup materializes read-only inspection copies at
# $OPENRIG_HOME/reference/policies/builtin/ (same chain as reference docs below).
if [ -d "$DAEMON_DIR/policies" ]; then
  cp -r "$DAEMON_DIR/policies" "$CLI_DIR/daemon/policies"
fi

# Reference docs: copy from repo root docs/reference/ into the assembled package
if [ -d "$REPO_ROOT/docs/reference" ]; then
  mkdir -p "$CLI_DIR/daemon/docs/reference"
  cp -r "$REPO_ROOT/docs/reference/"* "$CLI_DIR/daemon/docs/reference/"
fi

# RESOLVER-VISIBLE daemon (Q2 packaging fix). The cli's RUNTIME bare-specifier value-imports —
# await import("@openrig/daemon/{crash-cart,gateway-protocol,gateway-human-registry}") — resolve via
# @openrig/daemon's EXPORTS MAP, so the daemon must live where node's resolver looks:
# <cli>/node_modules/@openrig/daemon. (The <cli>/daemon dir above is resolver-INVISIBLE — it is the
# path the cli SPAWNS the daemon PROCESS from, not an import target.) @openrig/daemon is UNPUBLISHED,
# so packages/cli lists it in "bundledDependencies": npm pack ships THIS copy in the tarball and npm
# install uses it, never the 404 registry. We assemble a CLEAN copy (package.json + dist only) that
# REPLACES the dev workspace symlink. The daemon's own runtime deps (hono/tar/ulid/yaml/@hono/*) and
# better-sqlite3 (NATIVE — builds fresh on target, never prebuilt) are NOT nested here: the daemon dep
# set is a SUBSET of the cli's, so they stay HOISTED as the cli's own deps and resolve by node walking
# up to <cli>/node_modules.
DAEMON_NM="$CLI_DIR/node_modules/@openrig/daemon"
rm -rf "$DAEMON_NM"
mkdir -p "$DAEMON_NM/dist"
cp "$DAEMON_DIR/package.json" "$DAEMON_NM/package.json"
cp -r "$DAEMON_DIR/dist/"* "$DAEMON_NM/dist/"

# UI: dist
mkdir -p "$CLI_DIR/ui/dist"
cp -r "$UI_DIR/dist/"* "$CLI_DIR/ui/dist/"

# TUI: dist (public openrig-tui bin declared by the CLI package)
mkdir -p "$CLI_DIR/tui/dist"
cp -r "$TUI_DIR/dist/"* "$CLI_DIR/tui/dist/"

# Report
echo ""
echo "=== Package Assembled ==="
echo "CLI dist:        $(find "$CLI_DIR/dist" -name '*.js' | wc -l | tr -d ' ') JS files"
echo "Daemon dist:     $(find "$CLI_DIR/daemon/dist" -name '*.js' | wc -l | tr -d ' ') JS files"
echo "Daemon assets:   $(find "$CLI_DIR/daemon/assets" -type f 2>/dev/null | wc -l | tr -d ' ') files"
echo "Daemon specs:    $(find "$CLI_DIR/daemon/specs" -type f 2>/dev/null | wc -l | tr -d ' ') files"
echo "Daemon policies: $(find "$CLI_DIR/daemon/policies" -type f 2>/dev/null | wc -l | tr -d ' ') files"
echo "Daemon docs:     $(find "$CLI_DIR/daemon/docs" -type f 2>/dev/null | wc -l | tr -d ' ') files"
echo "UI dist:         $(find "$CLI_DIR/ui/dist" -type f | wc -l | tr -d ' ') files"
echo "TUI dist:        $(find "$CLI_DIR/tui/dist" -type f | wc -l | tr -d ' ') files"
echo ""
echo "Ready to publish: cd packages/cli && npm publish --access public"
