export {
  COMPOSER_PROMPT_CHARS,
  COMPOSER_PROMPT_CLASS,
  COMPOSER_SELECTION_PATTERN,
  COMPOSER_SELECTION_SCAN_PATTERN,
  COMPOSER_EMPTY_PATTERN,
  COMPOSER_EMPTY_CODEX_PLACEHOLDER_PATTERN,
  COMPOSER_DRAFT_PATTERN,
  COMPOSER_PROMPT_LINE_PATTERN,
  findComposerInputLineIndex,
  stripComposerPromptGlyph,
} from "./domain/composer-prompts.js";
